// Auto-generated by scripts/generate-build-info.mjs. Do not edit by hand.
// Commit this file so local typecheck works; release builds regenerate it.

export const BUILD_INFO = {
  "name": "casomira",
  "productName": "Časomíra",
  "version": "0.9.12-beta",
  "commitSha": "b96126d0a8ff0dce63e28504e731035190e34271",
  "shortCommitSha": "b96126d",
  "buildDate": "2026-06-15T15:27:08.408Z",
  "releaseChannel": "beta",
  "gitRef": "heroui-native",
  "packagedBy": "local"
} as const
