// Auto-generated by scripts/generate-build-info.mjs. Do not edit by hand.
// Commit this file so local typecheck works; release builds regenerate it.

export const BUILD_INFO = {
  "name": "verdict",
  "productName": "Verdict",
  "version": "0.9.13-beta",
  "commitSha": "24d3d52f034f459796b531400d8094182253f7c8",
  "shortCommitSha": "24d3d52",
  "buildDate": "2026-06-26T14:44:36.372Z",
  "releaseChannel": "beta",
  "gitRef": "verdict-ui-rebuild",
  "packagedBy": "local"
} as const
