// Auto-generated by scripts/generate-build-info.mjs. Do not edit by hand.
// Commit this file so local typecheck works; release builds regenerate it.

export const BUILD_INFO = {
  "name": "casomira",
  "productName": "Časomíra",
  "version": "0.9.11-beta",
  "commitSha": "e099ed473af2d4a2e2ebafc43dba045087f68586",
  "shortCommitSha": "e099ed4",
  "buildDate": "2026-06-12T11:21:12.162Z",
  "releaseChannel": "beta",
  "gitRef": "heroui-native",
  "packagedBy": "local"
} as const
